export const OperationalNotesFileName = [
    {
        name: "CVF",
        label: "Central Visual Field  (CVF)"
    },
    { name: "OCT", label: "OCT" },
    { name: "Fundus Photographs", label: "FundusPhotograph" },
    { name: "FFA", label: "FFA" }
];

export const LensTint = [
    "Amber",
    "Amethyst",
    "Aquamarine",
    "Autumn Gold",
    "Blue",
    "Brown",
    "Copper",
    "Didymium",
    "Green/Grey",
    "Grey",
    "Melanin",
    "Orange",
    "Pewter",
    "Pink",
    "Purple",
    "Rainbow",
    "Red",
    "Rose",
    "Sapphire",
    "Silver",
    "Tan",
    "Therannon",
    "Umber",
    "Yellow"
]

export const lensType = [
    "Adaptics - Photochromic",
    "Adapter micro brass",
    "BF - D Segment",
    "BF - Fused plastic",
    "BF - Invisible Bifocal",
    "BF - Invisible white focus",
    "Contact lens daily wear clear",
    "Contact lens Daily Colour",
    "Adapter transition lenses",
    "BF - Fused plastic lenses",
    "BF - Invisible Bifocal lenses",
    "BF - Invisible white lenses",
    "Contact lens daily wear white",
    "Contact Lens Daily Colour",
    "D-Top B-F Photo",
    "D-Top B-F White",
    "Disposable Contact Lens Colour",
    "D-Top B-F Photo",
    "D-Top B-F White",
    "Disposable Contact Lens colour",
    "Polaron with POA",
    "Polarized",
    "Progressive",
    "Progressive lens",
    "Single Vision Transition",
    "Single Vision with AR",
    "Single Vision Transition with AR",
    "Single Vision Ultra-Thin",
    "Single Vision Ultra-Thin transition",
    "Single Vision White",
    "Sunlenses",
    "Varilux Ellipse",
    "Varilux Ellipse transition",
    "Varilux progressive white lenses"
]